import Head from "next/head";
import React, { FC, ReactNode } from "react";
import Footer from "../UI/Footer/Footer";
import Header from "../UI/Header/Header";

import s from "./Layout.module.scss";

interface LayoutProps {
	children: ReactNode;
}

const Layout: FC<LayoutProps> = ({ children }) => (
	<>
		<Head>
			<title>Yoldi Profile</title>
			<meta name="description" content="Generated by create next app" />
			<meta
				name="viewport"
				content="width=device-width, initial-scale=1"
			/>
			<link rel="icon" href="/favicon.ico" />
		</Head>
		<div className={"page"}>
			<Header />
			<div className={s.content}>{children}</div>
			<Footer />
		</div>
	</>
);

export default Layout;
